### ISSUE TITLE
It's no longer work on latest vs code.

### ISSUE THREAD

**Issue by pakLebah** [vknabel/sourcekite#5] opened 2019-02-22 04:15 UTC
I build and install sourcekite on Mac Mojave with VS Code v.1.31.1, it no longer works. Here's the output of the extension execution from VS Code:

```
Debugger listening on ws://127.0.0.1:6004/87a5bc10-7f91-4e92-bb0f-58aa874124a5
For help, see: https://nodejs.org/en/docs/inspector
[Error - 11:11:00 AM] Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property 'on' of undefined
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/MacBee/Documents/Programs/swift/sourcekite/.build/release/ EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Info  - 11:11:00 AM] Connection to server got closed. Server will restart.
Debugger listening on ws://127.0.0.1:6004/ae422886-b707-44a9-b474-db6c8c5b9dbe
For help, see: https://nodejs.org/en/docs/inspector
[Error - 11:11:01 AM] Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property 'on' of undefined
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/MacBee/Documents/Programs/swift/sourcekite/.build/release/ EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Info  - 11:11:01 AM] Connection to server got closed. Server will restart.
Debugger listening on ws://127.0.0.1:6004/c81d9296-7da8-495b-8fc5-d7db7b5714e6
For help, see: https://nodejs.org/en/docs/inspector
[Error - 11:11:02 AM] Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property 'on' of undefined
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/MacBee/Documents/Programs/swift/sourcekite/.build/release/ EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Info  - 11:11:02 AM] Connection to server got closed. Server will restart.
Debugger listening on ws://127.0.0.1:6004/660f0ba3-ac46-498c-8b3d-99f43cd507b1
For help, see: https://nodejs.org/en/docs/inspector
[Error - 11:11:02 AM] Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property 'on' of undefined
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/MacBee/Documents/Programs/swift/sourcekite/.build/release/ EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Info  - 11:11:02 AM] Connection to server got closed. Server will restart.
Debugger listening on ws://127.0.0.1:6004/58eddef8-bfca-4a3f-ac7f-1e7ea3ef0d82
For help, see: https://nodejs.org/en/docs/inspector
[Error - 11:11:03 AM] Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property 'on' of undefined
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/MacBee/Documents/Programs/swift/sourcekite/.build/release/ EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Error - 11:11:03 AM] Connection to server got closed. Server will not be restarted.
```

Hope it'll be fixed soon. Thank you.

**Comment by vknabel** [comment] 2019-02-22 08:27
@pakLebah thanks for you report!

From reading your error, it seems like you have the following configuration:

```json
{
    "swift.path.sourcekite": "/Users/MacBee/Documents/Programs/swift/sourcekite/.build/release/"
}
```


Though you need to add a trailing `sourcekite` like here:

```json
{
    "swift.path.sourcekite": "/Users/MacBee/Documents/Programs/swift/sourcekite/.build/release/sourcekite"
}
```

I  hope this solves your issue.

**Comment by pakLebah** [comment] 2019-02-22 09:16
Yes, I fixed that a while after I posted this. It seems to be able to launch the sourcekite but the autocomplete still doesn't work. It just keep showing "Loading…" like forever.

**Comment by vknabel** [comment] 2019-03-15 16:03
@pakLebah sorry for the late answer. Could you already solve your issue?

When you have opened your Swift-project, does it show `build succeeded` in the status bar as shown below?

<img width="599" alt="Screenshot 2019-03-15 16 58 38" src="https://user-images.githubusercontent.com/2100336/54444802-c54c3e80-4743-11e9-971a-5a549f50a1b5.png">

What Swift version are you using?
May I ask which project and which file you opened?
What operating system do you use?

If I reproduce your issue within the same environment, it would help a lot debugging it.

**Comment by pakLebah** [comment] 2019-03-16 00:23
Never mind. I tried Apple's [sourcekit](https://github.com/apple/sourcekit-lsp) instead and then it "just works"™.

**Comment by vknabel** [comment] 2019-03-25 07:25
Glad you could find a working solution for you!

Closing this because I couldn’t reproduce it and we have a workaround for this. If this happens to someone else again, a simple restart of vscode might help.

**Comment by pakLebah** [comment] 2019-04-21 07:09
Just updated Apple's sourcekit to get Swift 5 support and I don't know why it took so much of CPU (160-180%) everytime it's about displaying the code completion panel.

So, I gave sourcekite another chance. After I installed and setup everything, it still doesn't work with the exact same problem as above, it's just showing `Loading…` like forever (after I hit `^space`). 😓 

![Jepretan Layar 2019-04-21 pukul 13 40 00](https://user-images.githubusercontent.com/11470932/56466665-bc374700-643e-11e9-83c0-b2324f0cbf44.png)

**Comment by vknabel** [comment] 2019-04-24 09:01
Hi @pakLebah!

Do you only have `test.swift` and `hello.swift` or do you have a target `hello` declared in your `Package.swift`-file? Because with Swift's-`import`, you can only import targets, not files. See https://www.raywenderlich.com/750-an-introduction-to-the-swift-package-manager

--- 
If you have a repo, could you send me a link to it? Thereafter you could enable logging for SDE.

```json
// .vscode/settings.json
{
  "sde.languageServerMode": "sourcekite",
  "sde.enableTracing.LSPServer": true,
  "sde.enableTracing.client": true
}
```

Then restart the vscode window. Play a bit around (only a bit to keep the output small) and in the output panel select `Swift`. Then upload all contents here (or better: in a gist).

It should look something like this:
<img width="1337" alt="Screenshot 2019-04-24 11 06 33" src="https://user-images.githubusercontent.com/2100336/56647060-19223f80-6681-11e9-9a6e-84636355dedf.png">

**Important:** Once you have finished recording the logs, make sure to either remove or set `sde.enableTracing.LSPServer` and `sde.enableTracing.client` to `false`. Otherwise you will have quite a strong performance impact.

**Comment by pakLebah** [comment] 2019-04-24 15:19
I don't use Package Manager, I compile my module manually. I knew about the module. The problem isn't with the module nor import. Even on a simple Hello World program that imports nothing, your extension behaves the same. It's loading like forever. Here's the screenshot:

![Jepretan Layar 2019-04-24 pukul 21 58 58](https://user-images.githubusercontent.com/11470932/56670076-5e278f80-66dc-11e9-8179-f90df7a30632.png)

After I enabled the tracing options, here's the output of Swift's panel (I tidy it up a bit):
```
Debugger listening on ws://127.0.0.1:6004/179f66a0-0ded-4c0d-92f8-5d289d147fb6
For help, see: https://nodejs.org/en/docs/inspector
[-->onInitialize ] isTracingOn=[true],
    skProtocolProcess=[/Users/MacBee/Programs/GitHub/sourcekite/.build/release/sourcekite],
    skProtocolProcessAsShellCmd=[false]
[-->onDidChangeConfiguration]
[-->onDidChangeConfiguration tracing:
    swiftDiverBinPath=[/usr/bin/swift],
    shellPath=[/bin/sh]]
[sourcekite] ***sourcekite initializing with skProtocolProcess at [/Users/MacBee/Programs/GitHub/sourcekite/.build/release/sourcekite]
[-->SourcekiteResponseHandler constructor done]
[ERROR][1]
[---onDidChangeContent]
[---onDidChangeContent]
[---onDidChangeContent]
[request] {
    key.request: source.request.codecomplete,
    key.sourcefile: "/Users/MacBee/Programs/swift/test.swift",
    key.offset: 27,
    key.compilerargs [
    "/Users/MacBee/Programs/swift/modules/hello.swift",
    "/Users/MacBee/Programs/swift/test.swift",
    "-target",
    "x86_64-apple-macosx10.10",
    "-sdk",
    "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
    ],
    key.sourcetext: "print(\"Hello world!\")\nprint"
}

[SourcekiteResponseHandler] 0
error response (Request Failed): error when parsing the compiler arguments
```

System I'm using:
• MacOS Mojave (10.14.4)
• XCode 10.2.1 (Swift 5)
• VS Code 1.33.1
• MSDE 2.7.1

Hope you can show me what's wrong with it. I know, it could be my mistake too.

**Comment by vknabel** [comment] 2019-04-26 15:09
I played a bit around. I found there is a missing `:` in your output. Was this really missing? Or did it get lost when pasting?

```diff
{
    key.request: source.request.codecomplete,
    key.sourcefile: "/Users/MacBee/Programs/swift/test.swift",
    key.offset: 27,
-   key.compilerargs [
+   key.compilerargs: [
    "/Users/MacBee/Programs/swift/modules/hello.swift",
    "/Users/MacBee/Programs/swift/test.swift",
    "-target",
    "x86_64-apple-macosx10.10",
    "-sdk",
    "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
    ],
    key.sourcetext: "print(\"Hello world!\")\nprint"
}
```


Could you try the following (trailing newlines are required):

```bash
$ /Users/MacBee/Programs/GitHub/sourcekite/.build/release/sourcekite
1
{
    key.request: source.request.codecomplete,
    key.sourcefile: "/Users/MacBee/Programs/swift/test.swift",
    key.offset: 27,
    key.compilerargs: [
    "/Users/MacBee/Programs/swift/modules/hello.swift",
    "/Users/MacBee/Programs/swift/test.swift",
    "-target",
    "x86_64-apple-macosx10.10",
    "-sdk",
    "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
    ],
    key.sourcetext: "print(\"Hello world!\")\nprint"
}



```

What is the result in your case?

**Comment by pakLebah** [comment] 2019-04-27 00:23
The semicolon was missing when I was tidying up the output. Sorry. It actually had the semicolon.

Here's the result:
```
$ /Users/MacBee/Programs/GitHub/sourcekite/.build/release/sourcekite
1
{
    key.request: source.request.codecomplete,
    key.sourcefile: "/Users/MacBee/Programs/swift/test.swift",
    key.offset: 27,
    key.compilerargs: [
    "/Users/MacBee/Programs/swift/modules/hello.swift",
    "/Users/MacBee/Programs/swift/test.swift",
    "-target",
    "x86_64-apple-macosx10.10",
    "-sdk",
    "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
    ],
    key.sourcetext: "print(\"Hello world!\")\nprint"
}

1
{
  key.results: [
    {
      key.kind: source.lang.swift.pattern,
      key.name: "(:)",
      key.sourcetext: "(<#T##items: Any...##Any#>)",
      key.description: "(items: Any...)",
      key.typename: "Void",
      key.context: source.codecompletion.context.thismodule,
      key.num_bytes_to_erase: 0
    },
    {
      key.kind: source.lang.swift.pattern,
      key.name: "(:separator:terminator:)",
      key.sourcetext: "(<#T##items: Any...##Any#>, separator: <#T##String#>, terminator: <#T##String#>)",
      key.description: "(items: Any..., separator: String, terminator: String)",
      key.typename: "Void",
      key.context: source.codecompletion.context.thismodule,
      key.num_bytes_to_erase: 0
    },
    {
      key.kind: source.lang.swift.keyword,
      key.name: "self",
      key.sourcetext: ".self",
      key.description: "self",
      key.typename: "(Any..., String, String) -> ()",
      key.context: source.codecompletion.context.thisclass,
      key.num_bytes_to_erase: 0
    }
  ]
}

```

It seems that it works. But I don't know why it doesn't work within VS Code. Here's from VS Code's Output panel:

```
Debugger listening on ws://127.0.0.1:6004/aa0188e2-1c66-4406-a013-c94270dc6d14
For help, see: https://nodejs.org/en/docs/inspector
[-->onInitialize ] isTracingOn=[true],
    skProtocolProcess=[/Users/MacBee/Programs/GitHub/sourcekite/.build/x86_64-apple-macosx/release/sourcekite],skProtocolProcessAsShellCmd=[false]
[-->onDidChangeConfiguration]
[-->onDidChangeConfiguration tracing:
    swiftDiverBinPath=[/usr/bin/swift],
    shellPath=[/bin/sh]]
[sourcekite] ***sourcekite initializing with skProtocolProcess at [/Users/MacBee/Programs/GitHub/sourcekite/.build/x86_64-apple-macosx/release/sourcekite]
[-->SourcekiteResponseHandler constructor done]
[ERROR][1]
[---onDidChangeContent]
[---onDidChangeContent]
[request] {
    key.request: source.request.codecomplete,
    key.sourcefile: "/Users/MacBee/Programs/swift/test.swift",
    key.offset: 61,
    key.compilerargs: [
    "/Users/MacBee/Programs/swift/modules/hello.swift",
    "/Users/MacBee/Programs/swift/test.swift",
    "-target","x86_64-apple-macosx10.10",
    "-sdk",
    "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
    ],
    key.sourcetext: "print(\"Hello world!\")\nprint"
}

[SourcekiteResponseHandler] 0
error response (Request Failed): error when parsing the compiler arguments
```

Anything wrong?

**Comment by vknabel** [comment] 2019-04-27 08:03
Thanks for the logs! I don't know what causes your bug, but at least I could find a way to reproduce the error:
when I manually inserted an invalid target, I received the `error response (Request Failed): error when parsing the compiler arguments`, too.

Can you compile your scripts with `-target x86_64-apple-macosx10.10` (SDE uses this as default on macOS)?

Additionally I found a workaround for your bug: you can manually specify targets.
The benefits in your case: as you compile your swift files manually anyway, you should already all compiler arguments. If you add multiple targets and link them manually, you should also receive quite good autocompletion results.

```jsonc
// .vscode/settings.json
{
  "swift.targets": [
    {
      "path": ".",
      "sources": ["**/*.swift"],
      "compilerArguments": [
        // make sure to replace this with your actual target, e.g. take it from `$ swift -version`
        "-target", "x86_64-apple-macosx10.10" 
        // you also might need to add a `-sdk` argument
      ]
    }
  ]
}
```

**Comment by pakLebah** [comment] 2019-04-28 09:12
Nope, the workaround also doesn't work, even after I add the `-sdk` argument. Same error. For now, I just disable MSDE completely since nothing seems to work. And I'm back to old school method, open the Swift docs and refs using Dash app.

**Comment by vknabel** [comment] 2019-04-30 07:20
That's sad to hear. Though I have to admit, I don't know how to help you. Maybe a future version of sourcekit-lsp or using SPM will solve your problems.

**Comment by pakLebah** [comment] 2019-04-30 08:45
It's alright. It just makes me wonder, what's wrong with my system that made your extension doesn't work? I got no problem with any other extensions, it's just yours.

**Closed as completed** 2022-08-23 12:28 UTC
